### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by justaskz** [chenkovsky/docopt.cr#4]
Getting this 

```
in ./src/app-test.cr:1: while requiring "docopt.cr": Error reading file: Is a directory

require "docopt.cr"
```

It seems that your module should be renamed to `docopt`. I did this in the `lib` folder and it started to work :)

**Comment by chenkovsky** [comment]
sorry, the document is confusing, my usage is `require "docopt.cr/docopt.cr"`, maybe renaming is a better idea.
